import AppKit
import Foundation

/// The clipboard history behind the `clipboard.read` capability. While a utility has recording on,
/// a light timer compares `NSPasteboard.changeCount` twice a second (macOS has no clipboard
/// notification, and this is the cheapest check there is). Only when it changes is the clipboard
/// read. Text and images are kept; files, and anything password managers mark concealed, transient
/// or auto-generated, are skipped, and so are apps the person chose to ignore. Everything lives in
/// the pack's own folder, `PackData/<id>-clipboard/`, and is deleted when the utility is removed.
final class ClipboardHistory {
    struct Item: Codable, Equatable {
        var id: String
        var kind: String              // "text", "image" or "file"
        var text: String?
        var width: Int?
        var height: Int?
        var bytes: Int
        var app: String?              // bundle id of the app it was copied in
        var appName: String?
        var at: Date
        var pinned: Bool
        /// The copied files' paths (kind "file"). Only where they are is kept, never the files.
        var files: [String]? = nil
    }

    struct Store: Codable {
        var items: [Item] = []
        var ignored: [String] = []          // bundle ids
        var apps: [String: String] = [:]    // bundle id → name, for the "ignore" picker
    }

    static let maxItems = 200
    static let maxImageBytes = 5 * 1024 * 1024
    static let maxTextLength = 100_000
    private static let skippedTypes: [NSPasteboard.PasteboardType] = [
        .init("org.nspasteboard.ConcealedType"), .init("org.nspasteboard.TransientType"),
        .init("org.nspasteboard.AutoGeneratedType"), .init("com.agilebits.onepassword"),
    ]

    private unowned let services: PackServices
    private var stores: [String: Store] = [:]
    private var watchers: [String: Timer] = [:]
    private var lastChange = NSPasteboard.general.changeCount
    /// Set when a utility copies an item back, so that copy doesn't come back as a new item.
    private var ownChange: Int?
    private var thumbnails: [String: NSImage] = [:]

    init(services: PackServices) { self.services = services }

    // MARK: Recording

    func isRecording(packID: String) -> Bool { watchers[packID] != nil }

    /// Starts or stops recording, and remembers the choice for the next launch.
    func setRecording(_ on: Bool, packID: String, packName: String) {
        services.defaults.set(on, forKey: "pack.\(packID).clipboard.recording")
        on ? start(packID: packID, packName: packName) : services.stop("\(packID).clipboard")
        services.changed()
    }

    /// At launch: carry on recording for utilities that were recording when Zephydian quit.
    func restore(packID: String, packName: String) {
        if services.defaults.bool(forKey: "pack.\(packID).clipboard.recording") { start(packID: packID, packName: packName) }
    }

    private func start(packID: String, packName: String) {
        guard watchers[packID] == nil else { return }
        lastChange = NSPasteboard.general.changeCount        // only what's copied from now on
        let timer = Timer(timeInterval: 0.5, repeats: true) { [weak self] _ in
            MainActor.assumeIsolated { self?.check(packID: packID) }
        }
        timer.tolerance = 0.25                                 // lets macOS batch the wake-ups
        RunLoop.main.add(timer, forMode: .common)
        watchers[packID] = timer
        services.started(.init(packID: packID, packName: packName, kind: "clipboard", detail: detail(packID), colorsJet: false)) { [weak self] in
            self?.watchers.removeValue(forKey: packID)?.invalidate()
            self?.services.defaults.set(false, forKey: "pack.\(packID).clipboard.recording")
            self?.services.changed()
        }
    }

    private func detail(_ packID: String) -> String {
        let n = store(packID).items.count
        return "Recording · \(n) item\(n == 1 ? "" : "s")"
    }

    private func check(packID: String) {
        let board = NSPasteboard.general
        guard board.changeCount != lastChange else { return }
        lastChange = board.changeCount
        if ownChange == board.changeCount { return }
        capture(from: board, packID: packID, app: NSWorkspace.shared.frontmostApplication)
    }

    /// Reads the clipboard once and adds what's worth keeping. Internal so tests can call it.
    func capture(from board: NSPasteboard, packID: String, app: NSRunningApplication?) {
        let types = board.types ?? []
        if types.contains(where: Self.skippedTypes.contains) { return }
        var s = store(packID)
        let appID = app?.bundleIdentifier
        if let appID {
            if s.ignored.contains(appID) { return }
            s.apps[appID] = app?.localizedName ?? appID
        }
        let now = Date()
        if types.contains(.fileURL),
           let urls = board.readObjects(forClasses: [NSURL.self], options: [.urlReadingFileURLsOnly: true]) as? [URL], !urls.isEmpty {
            let paths = urls.map(\.path)
            let pinned = s.items.first { $0.kind == "file" && $0.files == paths }?.pinned ?? false
            s.items.removeAll { $0.kind == "file" && $0.files == paths }       // a repeat moves to the top
            let names = urls.map { FileManager.default.displayName(atPath: $0.path) }
            let label = names.count == 1 ? names[0] : "\(names[0]) and \(names.count - 1) more"
            s.items.insert(Item(id: Self.newID(), kind: "file", text: label, bytes: 0, app: appID,
                                appName: app?.localizedName, at: now, pinned: pinned, files: paths), at: 0)
        } else if let text = board.string(forType: .string), !text.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty {
            var text = String(text.prefix(Self.maxTextLength))
            // With Clean URLs on, a copied link is kept without its tracking (the feature may not have cleaned it yet).
            if Features.shared.isOn("clean-url"), !text.contains(where: \.isWhitespace), let cleaned = URLCleaner.clean(text) { text = cleaned }
            let pinned = s.items.first { $0.kind == "text" && $0.text == text }?.pinned ?? false
            s.items.removeAll { $0.kind == "text" && $0.text == text }       // a repeat moves to the top
            s.items.insert(Item(id: Self.newID(), kind: "text", text: text, bytes: text.utf8.count, app: appID,
                                appName: app?.localizedName, at: now, pinned: pinned), at: 0)
        } else if let data = board.data(forType: .png) ?? board.data(forType: .tiff),
                  let rep = NSBitmapImageRep(data: data), let png = rep.representation(using: .png, properties: [:]),
                  png.count <= Self.maxImageBytes {
            let id = Self.newID()
            guard (try? write(png, to: imageURL(packID, id))) != nil else { return }
            s.items.insert(Item(id: id, kind: "image", width: rep.pixelsWide, height: rep.pixelsHigh, bytes: png.count,
                                app: appID, appName: app?.localizedName, at: now, pinned: false), at: 0)
        } else {
            return
        }
        trim(&s, packID: packID)
        save(s, packID: packID)
        services.update(packID: packID, kind: "clipboard", detail: detail(packID))
        services.changed()
    }

    // MARK: For the utility

    func items(packID: String, query: String) -> [Item] {
        let all = store(packID).items
        let pinned = all.filter(\.pinned), rest = all.filter { !$0.pinned }
        let q = query.trimmingCharacters(in: .whitespaces)
        return (pinned + rest).filter { q.isEmpty || ($0.text ?? "").localizedCaseInsensitiveContains(q) || ($0.appName ?? "").localizedCaseInsensitiveContains(q) }
    }

    /// Puts an item back on the clipboard (it isn't added again as a new item).
    /// The saved items, newest first (the Command Bar searches them).
    func items(packID: String) -> [Item] { store(packID).items }

    func copy(packID: String, id: String) -> Bool {
        guard let item = store(packID).items.first(where: { $0.id == id }) else { return false }
        let board = NSPasteboard.general
        board.clearContents()
        if item.kind == "file" {
            let urls = (item.files ?? []).map { URL(filePath: $0) }.filter { FileManager.default.fileExists(atPath: $0.path) }
            guard !urls.isEmpty else { return false }
            board.writeObjects(urls as [NSURL])
        } else if item.kind == "text", let text = item.text {
            board.setString(text, forType: .string)
        } else if let data = try? Data(contentsOf: imageURL(packID, id)) {
            board.setData(data, forType: .png)
            if let tiff = NSImage(data: data)?.tiffRepresentation { board.setData(tiff, forType: .tiff) }
        } else {
            return false
        }
        ownChange = board.changeCount
        return true
    }

    /// Puts an item on the clipboard and pastes it into the app you were in (the panel closes first).
    /// Needs Accessibility to press ⌘V; without it the item is only copied. Returns false if it couldn't be copied.
    func paste(packID: String, id: String) -> Bool {
        guard copy(packID: packID, id: id) else { return false }
        guard Permissions.shared.isGranted(.accessibility) else {
            Permissions.shared.request(.accessibility)
            return true
        }
        services.hidePanel()
        Task { @MainActor in
            try? await Task.sleep(for: .milliseconds(180))   // the app you were in is focused again
            EventTap.pressKey(CGKeyCode(9), flags: .maskCommand)   // ⌘V
        }
        return true
    }

    func pin(packID: String, id: String, _ on: Bool) {
        var s = store(packID)
        guard let i = s.items.firstIndex(where: { $0.id == id }) else { return }
        s.items[i].pinned = on
        trim(&s, packID: packID)
        save(s, packID: packID)
        services.changed()
    }

    func remove(packID: String, id: String) {
        var s = store(packID)
        s.items.removeAll { $0.id == id }
        try? FileManager.default.removeItem(at: imageURL(packID, id))
        save(s, packID: packID)
        services.update(packID: packID, kind: "clipboard", detail: detail(packID))
        services.changed()
    }

    /// Clears everything except pinned items.
    func clear(packID: String) {
        var s = store(packID)
        for item in s.items where !item.pinned && item.kind == "image" {
            try? FileManager.default.removeItem(at: imageURL(packID, item.id))
        }
        s.items.removeAll { !$0.pinned }
        save(s, packID: packID)
        services.update(packID: packID, kind: "clipboard", detail: detail(packID))
        services.changed()
    }

    /// Apps seen so far (and ignored ones), for the "ignore" list.
    func apps(packID: String) -> [(id: String, name: String, ignored: Bool)] {
        let s = store(packID)
        return Set(s.apps.keys).union(s.ignored).map { ($0, s.apps[$0] ?? $0, s.ignored.contains($0)) }
            .sorted { $0.name.localizedCaseInsensitiveCompare($1.name) == .orderedAscending }
    }

    func setIgnored(packID: String, app: String, _ on: Bool) {
        var s = store(packID)
        s.ignored.removeAll { $0 == app }
        if on { s.ignored.append(app) }
        save(s, packID: packID)
        services.changed()
    }

    /// A small image for the list (`clipboard:<id>` in the pack's view).
    func thumbnail(packID: String, id: String) -> NSImage? {
        let key = "\(packID)/\(id)"
        if let cached = thumbnails[key] { return cached }
        if let item = store(packID).items.first(where: { $0.id == id }), item.kind == "file" {
            // A copied file shows its icon (or, for one image file, a picture of it).
            guard let path = item.files?.first else { return nil }
            let icon = (item.files?.count == 1 ? NSImage(contentsOfFile: path) : nil) ?? NSWorkspace.shared.icon(forFile: path)
            thumbnails[key] = icon
            return icon
        }
        guard let image = NSImage(contentsOf: imageURL(packID, id)) else { return nil }
        thumbnails[key] = image
        return image
    }

    /// Removing the utility deletes its whole history.
    func removeData(packID: String) {
        services.stop("\(packID).clipboard")
        services.defaults.removeObject(forKey: "pack.\(packID).clipboard.recording")
        stores[packID] = nil
        thumbnails = thumbnails.filter { !$0.key.hasPrefix("\(packID)/") }
        try? FileManager.default.removeItem(at: folder(packID))
    }

    // MARK: Storage

    private func trim(_ s: inout Store, packID: String) {
        var kept = 0
        s.items = s.items.filter { item in
            if item.pinned { return true }
            kept += 1
            if kept <= Self.maxItems { return true }
            if item.kind == "image" { try? FileManager.default.removeItem(at: imageURL(packID, item.id)) }
            return false
        }
    }

    private func folder(_ packID: String) -> URL {
        services.dataDirectory.appending(path: "\(packID)-clipboard", directoryHint: .isDirectory)
    }

    private func imageURL(_ packID: String, _ id: String) -> URL { folder(packID).appending(path: "\(id).png") }

    private func store(_ packID: String) -> Store {
        if let s = stores[packID] { return s }
        let s = (try? Data(contentsOf: folder(packID).appending(path: "history.json")))
            .flatMap { try? JSONDecoder().decode(Store.self, from: $0) } ?? Store()
        stores[packID] = s
        return s
    }

    private func save(_ s: Store, packID: String) {
        stores[packID] = s
        try? write(try JSONEncoder().encode(s), to: folder(packID).appending(path: "history.json"))
    }

    private func write(_ data: Data, to url: URL) throws {
        try FileManager.default.createDirectory(at: url.deletingLastPathComponent(), withIntermediateDirectories: true)
        try data.write(to: url, options: .atomic)
    }

    private static func newID() -> String { String(UUID().uuidString.prefix(12)).lowercased() }
}
